### ISSUE TITLE
Make Task.Usage optional

### ISSUE THREAD

**Issue by moorereason** [omeid/kargar#1]
I would like to request that Task.Usage be made optional.  It appears that it's only used in the help output.  I don't really care to define a Usage string for all my tasks since I can do that with a comment in the Go code.  All it does for me is add a lot of extra content in the build script that would otherwise be rather concise.

PS - Thanks for your work on Slurp and friends.  I try to avoid Ruby and Node, so Slurp has been fun to play with.  Looking forward to trying out Kargar/Kar.

**Comment by omeid** [comment]
Hello @moorereason,

I totally appreciate your point of view, however, one of the main advantages of kargar + gonzo over alternative is going to be the ability to simply distributed a self contained static binary with your product. I think forcing people to write a short usage description per task is helpful because the end user may not always be able to see the source.

The other option is perhaps to make the documentation completely inline with Go, parse the source code and use comment association. However, that may not be possible without code generation and that is something that I want to avoid as I learned from Slurp that code generation for this case is less than optimal.

PS. You're welcome, I hope you enjoyed playing around with Slurp and so, as much I did writing them. :)
